# Generated by Django 5.1.7 on 2025-03-08 22:57

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comercial', '0007_detallepedido_tarifa_recuperacion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompraNacional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origen_compra', models.CharField(choices=[('Abastos', 'Abastos'), ('Exportadora', 'Exportadora'), ('Proveedor', 'Proveedor'), ('Otro', 'Otro')], max_length=20, verbose_name='Origen')),
                ('peso_compra', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Peso Guia/Compra')),
                ('fecha_compra', models.DateField(verbose_name='Fecha de Compra')),
                ('numero_guia', models.CharField(max_length=20, unique=True, verbose_name='Numero Guia')),
                ('remision', models.CharField(blank=True, default='Sin Remision', max_length=20, null=True, verbose_name='Remision')),
                ('precio_compra_exp', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='$ Compra Exp')),
                ('precio_compra_nal', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='$ Compra Nal')),
                ('cantidad_empaque', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cantidad Empaque')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('fruta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='comercial.fruta', verbose_name='Fruta')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Empaque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20, unique=True, verbose_name='Nombre Empaque')),
                ('peso', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Peso Empaque')),
            ],
        ),
        migrations.CreateModel(
            name='ProveedorNacional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='Nombre Proveedor')),
                ('nit', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Nit/C.C Proveedor')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefono Proveedor')),
                ('email', models.EmailField(blank=True, max_length=50, null=True, verbose_name='Email Proveedor')),
                ('asohofrucol', models.BooleanField(default=False, verbose_name='Asohofrucol 1%')),
                ('rte_fte', models.BooleanField(default=False, verbose_name='Rete Fuente 1,5%')),
                ('rte_ica', models.BooleanField(default=False, verbose_name='Rete Ica 4,14/1000')),
                ('regimen', models.CharField(blank=True, choices=[('Régimen Común', 'Régimen Común'), ('Régimen Simplificado', 'Régimen Simplificado'), ('Régimen Simple de Tributación', 'Régimen Simple de Tributación'), ('Régimen Especial', 'Régimen Especial')], max_length=30, null=True, verbose_name='Regimen')),
                ('ciudad', models.CharField(blank=True, max_length=50, null=True, verbose_name='Ciudad')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
            ],
        ),
        migrations.CreateModel(
            name='VentaNacional',
            fields=[
                ('compra_nacional', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='nacionales.compranacional', verbose_name='Compra Nacional')),
                ('fecha_llegada', models.DateField(verbose_name='Fecha de Llegada')),
                ('fecha_vencimiento', models.DateField(editable=False, verbose_name='Vencimiento Reporte')),
                ('cantidad_empaque_recibida', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cantidad Empaque Recibida')),
                ('peso_bruto_recibido', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Peso Bruto Recibido')),
                ('peso_neto_recibido', models.DecimalField(decimal_places=2, editable=False, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Peso Neto Recibido')),
                ('diferencia_peso', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Diferencia Peso')),
                ('diferencia_empaque', models.IntegerField(blank=True, editable=False, null=True, verbose_name='Diferencia Empaque')),
                ('estado_venta', models.CharField(default='En Proceso', editable=False, max_length=20, verbose_name='Estado Venta')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('exportador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='comercial.exportador', verbose_name='Exportador')),
            ],
            options={
                'ordering': ['-pk'],
            },
        ),
        migrations.AddField(
            model_name='compranacional',
            name='tipo_empaque',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nacionales.empaque', verbose_name='Tipo Empaque'),
        ),
        migrations.CreateModel(
            name='FacturacionExportadores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_factura', models.CharField(max_length=20, unique=True, verbose_name='No Factura')),
                ('fecha_factura', models.DateField(verbose_name='Fecha Factura')),
                ('peso_kg', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Peso Kg')),
                ('precio_kg', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='$ Kg')),
                ('precio_total', models.DecimalField(decimal_places=2, editable=False, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Total Factura')),
                ('exportador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='comercial.exportador', verbose_name='Exportador')),
                ('fruta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='comercial.fruta', verbose_name='Fruta')),
            ],
        ),
        migrations.AddField(
            model_name='compranacional',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nacionales.proveedornacional', verbose_name='Proveedor'),
        ),
        migrations.CreateModel(
            name='TransferenciasProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referencia', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Referencia')),
                ('fecha_transferencia', models.DateField(verbose_name='Fecha Transferencia')),
                ('valor_transferencia', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Valor Transferencia')),
                ('origen_transferencia', models.CharField(choices=[('Alianza', 'Alianza'), ('Mabelly Diaz', 'Mabelly Diaz'), ('Pedro Diaz Melo', 'Pedro Diaz Melo'), ('Valentina Garay', 'Valentina Garay')], max_length=20, verbose_name='Origen Transferencia')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nacionales.proveedornacional', verbose_name='Proveedor')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ReporteCalidadExportador',
            fields=[
                ('venta_nacional', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='nacionales.ventanacional', verbose_name='Venta Nacional')),
                ('remision_exp', models.CharField(blank=True, default='Sin Remision', max_length=20, null=True, verbose_name='Remision/Reporte')),
                ('fecha_reporte', models.DateField(verbose_name='Fecha Reporte Exp')),
                ('kg_totales', models.DecimalField(decimal_places=2, editable=False, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Kg Totales')),
                ('kg_exportacion', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Kg Exp')),
                ('porcentaje_exportacion', models.DecimalField(decimal_places=2, editable=False, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)], verbose_name='% Exp')),
                ('precio_venta_kg_exp', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='$ Kg Exp')),
                ('kg_nacional', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Kg Nal')),
                ('porcentaje_nacional', models.DecimalField(decimal_places=2, editable=False, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)], verbose_name='% Nal')),
                ('precio_venta_kg_nal', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='$ Kg Nal')),
                ('kg_merma', models.DecimalField(decimal_places=2, editable=False, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Kg Merma')),
                ('porcentaje_merma', models.DecimalField(decimal_places=2, editable=False, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)], verbose_name='% Merma')),
                ('precio_total', models.DecimalField(decimal_places=2, editable=False, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Total Factura')),
                ('factura', models.CharField(blank=True, max_length=20, null=True, verbose_name='Factura Heavens')),
                ('fecha_factura', models.DateField(blank=True, null=True, verbose_name='Fecha Factura')),
                ('vencimiento_factura', models.DateField(blank=True, editable=False, null=True, verbose_name='Vencimiento Factura')),
                ('pagado', models.BooleanField(blank=True, default=False, null=True, verbose_name='Pagado')),
                ('estado_reporte_exp', models.CharField(default='En Proceso', editable=False, max_length=20, verbose_name='Estado Reporte Exp')),
            ],
            options={
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='ReporteCalidadProveedor',
            fields=[
                ('rep_cal_exp', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='nacionales.reportecalidadexportador', verbose_name='Reporte Calidad Exportador')),
                ('p_fecha_reporte', models.DateField(auto_now_add=True, verbose_name='Fecha Reporte Prov')),
                ('p_kg_totales', models.DecimalField(decimal_places=2, editable=False, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Kg Totales')),
                ('p_kg_exportacion', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Kg Exp')),
                ('p_porcentaje_exportacion', models.DecimalField(decimal_places=2, editable=False, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)], verbose_name='% Exp')),
                ('p_precio_kg_exp', models.DecimalField(decimal_places=2, editable=False, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='$ Kg Exp')),
                ('p_kg_nacional', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Kg Nal')),
                ('p_porcentaje_nacional', models.DecimalField(decimal_places=2, editable=False, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)], verbose_name='% Nal')),
                ('p_precio_kg_nal', models.DecimalField(decimal_places=2, editable=False, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='$ Kg Nal')),
                ('p_kg_merma', models.DecimalField(decimal_places=2, editable=False, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Kg Merma')),
                ('p_porcentaje_merma', models.DecimalField(decimal_places=2, editable=False, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)], verbose_name='% Merma')),
                ('p_total_facturar', models.DecimalField(decimal_places=2, editable=False, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Total Facturar')),
                ('asohofrucol', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Asohofrucol 1%')),
                ('rte_fte', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Rte Fte 1.5%')),
                ('rte_ica', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Rte Ica 4.14/1000')),
                ('p_total_pagar', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Total A Pagar')),
                ('p_utilidad', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Utilidad')),
                ('p_porcentaje_utilidad', models.DecimalField(decimal_places=2, editable=False, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)], verbose_name='% Utilidad')),
                ('reporte_enviado', models.BooleanField(default=False, verbose_name='Reporte Enviado')),
                ('factura_prov', models.CharField(blank=True, max_length=20, null=True, verbose_name='No Factura Proveedor')),
                ('reporte_pago', models.BooleanField(default=False, verbose_name='Reporte Pago')),
                ('estado_reporte_prov', models.CharField(default='En Proceso', editable=False, max_length=50, verbose_name='Estado Reporte Prov')),
                ('completado', models.BooleanField(default=False, verbose_name='Completado')),
            ],
            options={
                'ordering': ['-pk'],
            },
        ),
    ]
