# Generated by Django 5.1.7 on 2025-03-16 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nacionales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportecalidadproveedor',
            name='reporte_pago',
            field=models.BooleanField(default=False, editable=False, verbose_name='Reporte Pago'),
        ),
        migrations.CreateModel(
            name='BalanceProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saldo_disponible', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Saldo Disponible')),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('proveedor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='nacionales.proveedornacional', verbose_name='Proveedor')),
            ],
            options={
                'verbose_name': 'Balance de Proveedor',
                'verbose_name_plural': 'Balances de Proveedores',
            },
        ),
    ]
