# Generated by Django 5.1.5 on 2025-02-21 01:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nacionales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventanacional',
            name='peso_bruto_recibido',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Peso Bruto Recibido'),
        ),
        migrations.AlterField(
            model_name='ventanacional',
            name='peso_neto_recibido',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Peso Neto Recibido'),
        ),
    ]
