# Generated by Django 5.1.5 on 2025-02-17 20:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nacionales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compranacional',
            name='precio_compra_nal',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='$ Compra Nal'),
        ),
        migrations.AlterField(
            model_name='reportecalidadproveedor',
            name='p_kg_exportacion',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Kg Exp'),
        ),
        migrations.AlterField(
            model_name='reportecalidadproveedor',
            name='p_kg_nacional',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Kg Nal'),
        ),
    ]
