# Generated by Django 5.2 on 2025-05-02 16:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nacionales', '0002_alter_reportecalidadproveedor_reporte_pago_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportecalidadproveedor',
            name='p_kg_totales',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Kg Totales'),
        ),
    ]
