# Generated by Django 5.1.5 on 2025-02-23 10:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nacionales', '0002_alter_ventanacional_peso_bruto_recibido_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportecalidadproveedor',
            name='p_asohofrucol',
        ),
        migrations.RemoveField(
            model_name='reportecalidadproveedor',
            name='p_rte_fuente',
        ),
        migrations.AddField(
            model_name='proveedornacional',
            name='asohofrucol',
            field=models.BooleanField(default=False, verbose_name='Asohofrucol 1%'),
        ),
        migrations.AddField(
            model_name='proveedornacional',
            name='rte_fte',
            field=models.BooleanField(default=False, verbose_name='Rete Fuente 1,5%'),
        ),
        migrations.AddField(
            model_name='proveedornacional',
            name='rte_ica',
            field=models.BooleanField(default=False, verbose_name='Rete Ica 4,14/1000'),
        ),
        migrations.AddField(
            model_name='reportecalidadproveedor',
            name='asohofrucol',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Asohofrucol 1%'),
        ),
        migrations.AddField(
            model_name='reportecalidadproveedor',
            name='rte_fte',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Rte Fte 1.5%'),
        ),
        migrations.AddField(
            model_name='reportecalidadproveedor',
            name='rte_ica',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Rte Ica 4.14/1000'),
        ),
    ]
