# Generated by Django 5.1.5 on 2025-02-19 00:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nacionales', '0002_alter_compranacional_precio_compra_nal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventanacional',
            name='diferencia_empaque',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Diferencia Empaque'),
        ),
    ]
