# Generated by Django 5.2.1 on 2025-05-18 23:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nacionales', '0003_alter_reportecalidadproveedor_p_kg_totales'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportecalidadexportador',
            name='pagado',
        ),
        migrations.AddField(
            model_name='reportecalidadproveedor',
            name='diferencia_utilidad',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, editable=False, max_digits=10, null=True, verbose_name='Diferencia Utilidad'),
        ),
        migrations.AddField(
            model_name='reportecalidadproveedor',
            name='monto_pendiente',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Monto Pendiente'),
        ),
        migrations.AddField(
            model_name='reportecalidadproveedor',
            name='p_utilidad_sin_ajuste',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, editable=False, max_digits=10, null=True, verbose_name='Utilidad Sin Ajuste'),
        ),
        migrations.AlterField(
            model_name='reportecalidadexportador',
            name='estado_reporte_exp',
            field=models.CharField(default='Pendiente', editable=False, max_length=20, verbose_name='Estado Reporte Exp'),
        ),
        migrations.AlterField(
            model_name='reportecalidadproveedor',
            name='completado',
            field=models.BooleanField(default=False, editable=False, verbose_name='Completado'),
        ),
        migrations.AlterField(
            model_name='reportecalidadproveedor',
            name='p_utilidad',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, verbose_name='Utilidad'),
        ),
        migrations.AlterField(
            model_name='ventanacional',
            name='estado_venta',
            field=models.CharField(default='Pendiente', editable=False, max_length=20, verbose_name='Estado Reporte (Exportador)'),
        ),
        migrations.DeleteModel(
            name='FacturacionExportadores',
        ),
    ]
