# Generated by Django 5.1.5 on 2025-02-23 20:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nacionales', '0003_remove_reportecalidadproveedor_p_asohofrucol_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compranacional',
            name='peso_compra',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Peso Guia/Compra'),
        ),
        migrations.AlterField(
            model_name='reportecalidadexportador',
            name='kg_merma',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Kg Merma'),
        ),
        migrations.AlterField(
            model_name='reportecalidadexportador',
            name='precio_total',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Total Factura'),
        ),
        migrations.AlterField(
            model_name='reportecalidadproveedor',
            name='p_kg_merma',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Kg Merma'),
        ),
        migrations.AlterField(
            model_name='reportecalidadproveedor',
            name='p_total_facturar',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Total Facturar'),
        ),
    ]
