# Generated by Django 5.1.5 on 2025-02-20 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nacionales', '0003_ventanacional_diferencia_empaque'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='compranacional',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='reportecalidadexportador',
            options={'ordering': ['-pk']},
        ),
        migrations.AlterModelOptions(
            name='reportecalidadproveedor',
            options={'ordering': ['-pk']},
        ),
        migrations.AlterModelOptions(
            name='ventanacional',
            options={'ordering': ['-pk']},
        ),
        migrations.AddField(
            model_name='reportecalidadexportador',
            name='finalizado',
            field=models.BooleanField(default=False, verbose_name='Finalizado'),
        ),
    ]
