# Generated by Django 5.1.5 on 2025-02-24 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nacionales', '0004_alter_compranacional_peso_compra_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transferenciasproveedor',
            options={'ordering': ['-id']},
        ),
        migrations.AlterField(
            model_name='ventanacional',
            name='fecha_vencimiento',
            field=models.DateField(editable=False, verbose_name='Vencimiento Reporte'),
        ),
        migrations.DeleteModel(
            name='PreciosGlobalesExportacion',
        ),
    ]
