# Generated by Django 6.0 on 2025-12-28 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nacionales', '0004_remove_reportecalidadexportador_pagado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transferenciasproveedor',
            name='origen_transferencia',
            field=models.CharField(choices=[('Alianza', 'Alianza'), ('Mabelly Diaz', 'Mabelly Diaz'), ('Pedro Diaz Melo', 'Pedro Diaz Melo'), ('Valentina Garay', 'Valentina Garay'), ('HEAVENS CO', 'HEAVENS CO')], max_length=20, verbose_name='Origen Transferencia'),
        ),
    ]
