# Generated by Django 5.1.5 on 2025-03-01 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nacionales', '0005_alter_transferenciasproveedor_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportecalidadexportador',
            name='remision_exp',
            field=models.CharField(blank=True, default='Sin Remision', max_length=20, null=True, verbose_name='Remision/Reporte'),
        ),
        migrations.AlterField(
            model_name='ventanacional',
            name='diferencia_empaque',
            field=models.IntegerField(blank=True, editable=False, null=True, verbose_name='Diferencia Empaque'),
        ),
    ]
