# Generated by Django Migration Tool
# Custom migration to convert VentaNacional from OneToOneField primary key to ForeignKey

from django.db import migrations, models
import django.db.models.deletion
from django.core.validators import MinValueValidator


def preserve_venta_ids(apps, schema_editor):
    """
    This function runs AFTER the schema changes.
    It ensures that the new 'id' field values match the old compra_nacional_id values
    for existing records to preserve referential integrity.
    
    Since we're using SeparateDatabaseAndState, the actual ID values should be preserved
    by the RunSQL operations below.
    """
    pass  # The RunSQL handles this


def noop(apps, schema_editor):
    """Reverse operation - no-op as schema handles it."""
    pass


class Migration(migrations.Migration):
    # Disable atomic mode to allow each operation to commit separately
    # This is required because PostgreSQL can't do some ALTER TABLE operations
    # when there are pending trigger events from previous operations in the same transaction
    atomic = False

    dependencies = [
        ('nacionales', '0005_alter_transferenciasproveedor_origen_transferencia'),
        ('comercial', '0001_initial'),
    ]

    operations = [
        # Step 1: Add new fields 'tipo' and 'lote' to VentaNacional (if they don't exist)
        migrations.RunSQL(
            sql="""
                DO $$
                BEGIN
                    IF NOT EXISTS (
                        SELECT 1 FROM information_schema.columns 
                        WHERE table_name = 'nacionales_ventanacional' AND column_name = 'tipo'
                    ) THEN
                        ALTER TABLE nacionales_ventanacional ADD COLUMN tipo VARCHAR(20) NULL;
                    END IF;
                    
                    IF NOT EXISTS (
                        SELECT 1 FROM information_schema.columns 
                        WHERE table_name = 'nacionales_ventanacional' AND column_name = 'lote'
                    ) THEN
                        ALTER TABLE nacionales_ventanacional ADD COLUMN lote VARCHAR(30) NULL;
                    END IF;
                END $$;
            """,
            reverse_sql="""
                ALTER TABLE nacionales_ventanacional DROP COLUMN IF EXISTS tipo;
                ALTER TABLE nacionales_ventanacional DROP COLUMN IF EXISTS lote;
            """,
            state_operations=[
                migrations.AddField(
                    model_name='ventanacional',
                    name='tipo',
                    field=models.CharField(
                        blank=True,
                        choices=[('Mango Europa', 'Mango Europa'), ('Otros Destinos', 'Otros Destinos')],
                        max_length=20,
                        null=True,
                        verbose_name='Tipo'
                    ),
                ),
                migrations.AddField(
                    model_name='ventanacional',
                    name='lote',
                    field=models.CharField(
                        blank=True,
                        max_length=30,
                        null=True,
                        verbose_name='Lote'
                    ),
                ),
            ],
        ),
        
        # Step 2: Drop foreign key constraints that reference VentaNacional's PK (if exists)
        migrations.RunSQL(
            sql="""
                -- Drop the FK from ReporteCalidadExportador to VentaNacional (all possible names)
                ALTER TABLE nacionales_reportecalidadexportador 
                DROP CONSTRAINT IF EXISTS nacionales_reporteca_venta_nacional_id_1415bbc4_fk_nacionale;
                
                ALTER TABLE nacionales_reportecalidadexportador 
                DROP CONSTRAINT IF EXISTS nacionales_reporteca_venta_nacional_id_fk;
                
                ALTER TABLE nacionales_reportecalidadexportador
                DROP CONSTRAINT IF EXISTS nacionales_reportecalidadexportad_venta_nacional_id_1415bbc4_uniq;
                
                ALTER TABLE nacionales_reportecalidadexportador
                DROP CONSTRAINT IF EXISTS nacionales_reportecalidadexportador_venta_nacional_id_key;
            """,
            reverse_sql="",
            state_operations=[],
        ),
        
        # Step 3: Add a new 'id' column to VentaNacional (if it doesn't exist)
        migrations.RunSQL(
            sql="""
                DO $$
                BEGIN
                    IF NOT EXISTS (
                        SELECT 1 FROM information_schema.columns 
                        WHERE table_name = 'nacionales_ventanacional' AND column_name = 'id'
                    ) THEN
                        ALTER TABLE nacionales_ventanacional ADD COLUMN id SERIAL;
                        UPDATE nacionales_ventanacional SET id = compra_nacional_id;
                    END IF;
                END $$;
                
                -- Update the sequence to start after the max existing ID
                SELECT setval(pg_get_serial_sequence('nacionales_ventanacional', 'id'), 
                              COALESCE((SELECT MAX(id) FROM nacionales_ventanacional), 0) + 1, false);
            """,
            reverse_sql="""
                ALTER TABLE nacionales_ventanacional DROP COLUMN IF EXISTS id;
            """,
            state_operations=[],
        ),
        
        # Step 4: Ensure id is the primary key
        migrations.RunSQL(
            sql="""
                -- Check if id is already the primary key
                DO $$
                DECLARE
                    pk_column text;
                BEGIN
                    -- Get the current primary key column
                    SELECT a.attname INTO pk_column
                    FROM pg_index i
                    JOIN pg_attribute a ON a.attrelid = i.indrelid AND a.attnum = ANY(i.indkey)
                    WHERE i.indrelid = 'nacionales_ventanacional'::regclass
                    AND i.indisprimary;
                    
                    -- If the PK is still on compra_nacional_id, switch it to id
                    IF pk_column = 'compra_nacional_id' THEN
                        ALTER TABLE nacionales_ventanacional DROP CONSTRAINT nacionales_ventanacional_pkey;
                        ALTER TABLE nacionales_ventanacional ADD PRIMARY KEY (id);
                    END IF;
                END $$;
            """,
            reverse_sql="""
                ALTER TABLE nacionales_ventanacional DROP CONSTRAINT IF EXISTS nacionales_ventanacional_pkey;
                ALTER TABLE nacionales_ventanacional ADD PRIMARY KEY (compra_nacional_id);
            """,
            state_operations=[],
        ),
        
        # Step 5: Ensure FK from VentaNacional to CompraNacional exists with correct constraint
        migrations.RunSQL(
            sql="""
                -- Remove the unique constraint on compra_nacional_id if exists (from OneToOneField)
                ALTER TABLE nacionales_ventanacional
                DROP CONSTRAINT IF EXISTS nacionales_ventanacional_compra_nacional_id_key;
                
                -- Rename old FK constraint if needed
                DO $$ 
                BEGIN
                    IF NOT EXISTS (
                        SELECT 1 FROM pg_constraint 
                        WHERE conname = 'nacionales_ventanac_compra_nacional_id_fk'
                        AND conrelid = 'nacionales_ventanacional'::regclass
                    ) THEN
                        -- Check if old FK exists and drop it first
                        ALTER TABLE nacionales_ventanacional
                        DROP CONSTRAINT IF EXISTS nacionales_ventanaci_compra_nacional_id_7903cd96_fk_nacionale;
                        
                        -- Create new FK
                        ALTER TABLE nacionales_ventanacional
                        ADD CONSTRAINT nacionales_ventanac_compra_nacional_id_fk
                        FOREIGN KEY (compra_nacional_id) 
                        REFERENCES nacionales_compranacional(id)
                        ON DELETE CASCADE;
                    END IF;
                END $$;
                
                -- Create index on compra_nacional_id for faster lookups
                CREATE INDEX IF NOT EXISTS nacionales_ventanacional_compra_nacional_id_idx 
                ON nacionales_ventanacional(compra_nacional_id);
            """,
            reverse_sql="""
                DROP INDEX IF EXISTS nacionales_ventanacional_compra_nacional_id_idx;
                ALTER TABLE nacionales_ventanacional DROP CONSTRAINT IF EXISTS nacionales_ventanac_compra_nacional_id_fk;
            """,
            state_operations=[],
        ),
        
        # Step 6: Recreate the FK from ReporteCalidadExportador to VentaNacional's id
        migrations.RunSQL(
            sql="""
                -- Add the FK constraint back if it doesn't exist
                DO $$ 
                BEGIN
                    IF NOT EXISTS (
                        SELECT 1 FROM pg_constraint 
                        WHERE conname = 'nacionales_reporteca_venta_nacional_id_fk'
                        AND conrelid = 'nacionales_reportecalidadexportador'::regclass
                    ) THEN
                        ALTER TABLE nacionales_reportecalidadexportador
                        ADD CONSTRAINT nacionales_reporteca_venta_nacional_id_fk
                        FOREIGN KEY (venta_nacional_id) 
                        REFERENCES nacionales_ventanacional(id)
                        ON DELETE CASCADE;
                    END IF;
                END $$;
            """,
            reverse_sql="""
                ALTER TABLE nacionales_reportecalidadexportador
                DROP CONSTRAINT IF EXISTS nacionales_reporteca_venta_nacional_id_fk;
            """,
            state_operations=[],
        ),
        
        # Step 7: Update Django's state to reflect the new schema
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                # Change field from OneToOneField to ForeignKey
                migrations.AlterField(
                    model_name='ventanacional',
                    name='compra_nacional',
                    field=models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='ventas',
                        to='nacionales.compranacional',
                        verbose_name='Compra Nacional'
                    ),
                ),
            ],
        ),
        
        # Step 8: Run the data preservation function (optional, for validation)
        migrations.RunPython(preserve_venta_ids, noop),
    ]
