# Generated by Django 5.1.5 on 2025-03-01 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nacionales', '0006_alter_reportecalidadexportador_remision_exp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportecalidadexportador',
            name='estado_reporte_exp',
            field=models.CharField(default='En Proceso', max_length=20, verbose_name='Estado Reporte Exp'),
        ),
        migrations.AddField(
            model_name='reportecalidadproveedor',
            name='estado_reporte_prov',
            field=models.CharField(default='En Proceso', editable=False, max_length=20, verbose_name='Estado Reporte Prov'),
        ),
        migrations.AddField(
            model_name='reportecalidadproveedor',
            name='factura_prov',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='No Factura Proveedor'),
        ),
        migrations.AddField(
            model_name='reportecalidadproveedor',
            name='reporte_enviado',
            field=models.BooleanField(default=False, editable=False, verbose_name='Reporte Enviado'),
        ),
        migrations.AddField(
            model_name='reportecalidadproveedor',
            name='reporte_pago',
            field=models.BooleanField(default=False, editable=False, verbose_name='Reporte Pago'),
        ),
        migrations.AddField(
            model_name='ventanacional',
            name='estado_venta',
            field=models.CharField(default='En Proceso', max_length=20, verbose_name='Estado Venta'),
        ),
        migrations.AlterField(
            model_name='reportecalidadexportador',
            name='finalizado',
            field=models.BooleanField(default=False, editable=False, verbose_name='Pagado'),
        ),
    ]
