# Generated by Django 6.0 on 2026-03-13 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nacionales', '0006_alter_ventanacional_to_foreignkey'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventanacional',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
