# Generated by Django 6.0 on 2026-03-20 19:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nacionales', '0007_ventanacional_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportecalidadproveedor',
            name='p_precio_kg_nal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='$ Kg Nal'),
        ),
    ]
