# Generated by Django 5.1.5 on 2025-03-01 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nacionales', '0007_reportecalidadexportador_estado_reporte_exp_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reportecalidadexportador',
            old_name='finalizado',
            new_name='pagado',
        ),
        migrations.AlterField(
            model_name='ventanacional',
            name='estado_venta',
            field=models.CharField(default='En Proceso', editable=False, max_length=20, verbose_name='Estado Venta'),
        ),
    ]
