# Generated by Django 5.1.5 on 2025-03-01 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nacionales', '0008_rename_finalizado_reportecalidadexportador_pagado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportecalidadproveedor',
            name='completado',
            field=models.BooleanField(default=False, verbose_name='Completado'),
        ),
        migrations.AlterField(
            model_name='reportecalidadexportador',
            name='estado_reporte_exp',
            field=models.CharField(default='En Proceso', editable=False, max_length=20, verbose_name='Estado Reporte Exp'),
        ),
        migrations.AlterField(
            model_name='reportecalidadexportador',
            name='pagado',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Pagado'),
        ),
        migrations.AlterField(
            model_name='reportecalidadproveedor',
            name='reporte_enviado',
            field=models.BooleanField(default=False, verbose_name='Reporte Enviado'),
        ),
        migrations.AlterField(
            model_name='reportecalidadproveedor',
            name='reporte_pago',
            field=models.BooleanField(default=False, verbose_name='Reporte Pago'),
        ),
    ]
