# Generated by Django 5.1.5 on 2025-03-01 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nacionales', '0009_reportecalidadproveedor_completado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportecalidadproveedor',
            name='estado_reporte_prov',
            field=models.CharField(default='En Proceso', editable=False, max_length=50, verbose_name='Estado Reporte Prov'),
        ),
    ]
