# Generated by Django 5.1.5 on 2025-03-02 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nacionales', '0010_alter_reportecalidadproveedor_estado_reporte_prov'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedornacional',
            name='regimen',
            field=models.CharField(blank=True, choices=[('Régimen Común', 'Régimen Común'), ('Régimen Simplificado', 'Régimen Simplificado'), ('Régimen Simple de Tributación', 'Régimen Simple de Tributación'), ('Régimen Especial', 'Régimen Especial')], max_length=30, null=True, verbose_name='Regimen'),
        ),
    ]
