# Generated by Django 5.1.5 on 2025-03-03 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nacionales', '0011_proveedornacional_regimen'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedornacional',
            name='nit',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Nit/C.C Proveedor'),
        ),
    ]
