# Generated by Django 5.1.5 on 2025-03-03 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nacionales', '0012_proveedornacional_nit'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferenciasproveedor',
            name='referencia',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Referencia'),
        ),
    ]
