# Generated by Django 5.1.5 on 2025-03-04 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nacionales', '0013_transferenciasproveedor_referencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedornacional',
            name='ciudad',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Ciudad'),
        ),
    ]
