# nixpacks.toml

[phases.setup]
# Instalar Python 3.11 y los paquetes de Nix
nixPkgs = [
  "python311",
  "pkg-config",
  "glib",
  "cairo",
  "pango",
  "gobject-introspection"
]

# Instalar paquetes de apt-get si es necesario
aptPkgs = [
  "build-essential",
  "libcairo2",
  "libcairo2-dev",
  "libgirepository1.0-dev",
  "gir1.2-pango-1.0",
  "gir1.2-gtk-3.0",
  "python3-gi",
  "shared-mime-info"
]

[phases.install]
# Instalar las dependencias de Python
cmds = ["pip install -r requirements.txt"]

[phases.build]
# Colectar archivos estáticos y migrar la base de datos
cmds = ["python manage.py collectstatic --noinput", "python manage.py migrate"]

[start]
# Comando para iniciar la aplicación
cmd = "gunicorn mysite.wsgi"
