# nixpacks.toml

[phases.setup]
# Instalar Python 3.11 y los paquetes de Nix
nixPkgs = [
  "python312"
]

# Instalar paquetes de apt-get si es necesario
aptPkgs = [
  "build-essential",
  "libcairo2",
  "libffi-dev",
  "shared-mime-info",
  "libjpeg-dev",  # Necesario para manejo de imágenes en PDF
  "zlib1g-dev",  # Necesario para compresión de imágenes en PDF
  "libfreetype6-dev",  # Necesario para manejo de fuentes
  "liblcms2-dev",  # Necesario para manejo de perfiles de color
  "libopenjpeg-dev",  # Necesario para manejo de imágenes JPEG2000
  "libtiff5-dev",  # Necesario para manejo de imágenes TIFF
  "libwebp-dev"  # Necesario para manejo de imágenes WebP
]

[phases.python_install]
    dependsOn = ['setup']
    cmds = ['pip install -r requirements.txt']

[phases.build]
# Colectar archivos estáticos y migrar la base de datos
cmds = ["python manage.py collectstatic --noinput", "python manage.py migrate"]

[start]
# Comando para iniciar la aplicación
cmd = "gunicorn mysite.wsgi"
