def reporte_individual_proveedor(request, proveedor_id):
    # ...existing code...
    reporte = {
        # ...existing code...
        # 'valor_promedio_kg': some_value,  # Línea eliminada
        # ...existing code...
    }
    # ...existing code...
