"""
Django settings for mysite project.

Generated by 'django-admin startproject' using Django 4.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

import os
import dj_database_url
from dotenv import load_dotenv
from pathlib import Path
from django.templatetags.static import static
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _
from django.core.exceptions import ImproperlyConfigured
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-rc^*w^w&6g9_(uvx#6s*bnt!w)l0rdi%!l7mv#y%uc&x%wo5pk'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

# FORM SUBMISSION
# Comment out the following line and place your railway URL, and your production URL in the array.
# CSRF_TRUSTED_ORIGINS = ["*"]

# Application definition

INSTALLED_APPS = [
    'autenticacion.apps.AutenticacionConfig',
    'unfold',
    'unfold.contrib.filters',
    'unfold.contrib.inlines',
    'unfold.contrib.import_export',
    'unfold.contrib.simple_history',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.sites',  # Added for sitemaps
    'django.contrib.sitemaps',  # Added for sitemaps
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'django_tables2',
    'crispy_forms',
    'crispy_bootstrap5',
    'import_export',
    'rest_framework',
    'django_extensions',
    'simple_history',
    'widget_tweaks',
    'cartera.apps.CarteraConfig',
    'comercial.apps.ComercialConfig',
    'inventarios.apps.InventariosConfig',
    'nacionales.apps.NacionalesConfig',
    'captcha',
]

SITE_ID = 1  # Added for sitemaps

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
]

ROOT_URLCONF = 'mysite.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, 'autenticacion', 'templates'),
            os.path.join(BASE_DIR, 'autenticacion', 'templates', 'registration'),
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'mysite.wsgi.application'

# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases


# Configuración optimizada de base de datos para prevenir timeouts
DATABASE_CONFIG = dj_database_url.config(default=os.getenv('DATABASE_PRIVATE_URL'))

# Añadir configuraciones de optimización
DATABASE_CONFIG.update({
    'CONN_MAX_AGE': 60,   # Reducido a 1 minuto para liberar conexiones más rápido
    'OPTIONS': {
        'connect_timeout': 30,
        'options': '-c statement_timeout=300000'  # 5 minutos timeout para queries
    }
})

DATABASES = {
    'default': DATABASE_CONFIG
}

# Configuración de cache para optimizar memoria
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'unique-snowflake',
        'OPTIONS': {
            'MAX_ENTRIES': 1000,  # Limitar entradas para controlar memoria
            'CULL_FREQUENCY': 4,  # Eliminar 1/4 de las entradas cuando se alcanza MAX_ENTRIES
        }
    }
}

# Configuración de sesiones optimizada para memoria
SESSION_ENGINE = 'django.contrib.sessions.backends.cached_db'
SESSION_CACHE_ALIAS = 'default'
SESSION_COOKIE_AGE = 3600  # 1 hora en lugar de 2 semanas por defecto

# Configuración de logging optimizada para memoria
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
            'level': 'WARNING',  # Solo warnings y errores
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'WARNING',
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'WARNING',
            'propagate': False,
        },
        'django.db.backends': {
            'handlers': [],  # Desactivar logs de DB para ahorrar memoria
            'level': 'WARNING',
            'propagate': False,
        },
    },
}

"""
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'heavens_local',  # Nombre de tu base de datos
        'USER': 'postgres',  # Nombre de usuario de tu base de datos
        'PASSWORD': 'Sebastyk120',  # Contraseña del usuario de la base de datos
        'HOST': 'localhost',  # Deja esto como 'localhost' si estás ejecutando PostgreSQL localmente
        'PORT': '5432',  # Puerto de PostgreSQL (por defecto es 5432)
    }
}"""

# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization

LANGUAGE_CODE = 'es-es'
TIME_ZONE = 'America/Bogota'
USE_I18N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, "static")]
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")
LOGIN_URL = 'login'

# WhiteNoise configuration
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
WHITENOISE_USE_FINDERS = True
WHITENOISE_MANIFEST_STRICT = False
WHITENOISE_ALLOW_ALL_ORIGINS = True

# Media files configuration
MEDIA_URL = '/media/'
if DEBUG:
    MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
else:
    # En producción usamos la ruta montada
    MEDIA_ROOT = '/media'

# Añadir esta línea para que Whitenoise sirva archivos de medios en producción
WHITENOISE_ROOT = MEDIA_ROOT

# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"

ALLOWED_HOSTS = [
    'heavens-server-private.up.railway.app', 'localhost',
    'heavensfruit.com', 'www.heavensfruit.com',
]
CSRF_TRUSTED_ORIGINS = ["https://*.up.railway.app", "https://*.heavensfruit.com"]

CORS_ORIGINS_WHITELIST = ["https://heavens-server-private.up.railway.app",
                          "https://heavensfruit.com",
                          "https://www.heavensfruit.com",]

# Configuración adicional de sesiones para optimizar memoria
SESSION_EXPIRE_AT_BROWSER_CLOSE = True
SESSION_SAVE_EVERY_REQUEST = False  # No guardar sesión en cada request
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SECURE = True  # Solo HTTPS en producción
SESSION_COOKIE_SAMESITE = 'Lax'

# CONFIGURACIÓN MAIL:
DEFAULT_FROM_EMAIL = "subgerencia@heavensfruit.com"
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.office365.com'
EMAIL_USE_TLS = True
EMAIL_PORT = 587
EMAIL_HOST_USER = DEFAULT_FROM_EMAIL
try:
    EMAIL_HOST_PASSWORD = os.environ['EMAIL_HOST_PASSWORD']
except KeyError:
    raise ImproperlyConfigured('La variable de entorno EMAIL_HOST_PASSWORD no está definida')
ADMIN_SITE_NAME = 'Administración Heavens Fruits'

# Unfold Configuration
UNFOLD = {
    "SITE_TITLE": "Heavens Fruits",
    "SITE_HEADER": "Heavens Fruits SAS",
    "SITE_SUBHEADER": "Heavens Fruits SAS",
    "SITE_URL": "/",
    "SITE_ICON": {
        "light": lambda request: static("img/favicon.ico"),
        "dark": lambda request: static("img/favicon.ico"),
    },
    "SITE_LOGO": {
        "light": lambda request: static("img/favicon.ico"),
        "dark": lambda request: static("img/favicon.ico"),
    },
    "SITE_SYMBOL": "agriculture",
    "SITE_FAVICONS": [
        {
            "rel": "icon",
            "sizes": "48x48",
            "href": lambda request: static("img/favicon.ico"),
        },
    ],
    "SHOW_HISTORY": True,
    "SHOW_VIEW_ON_SITE": True,
    "SHOW_BACK_BUTTON": True,
    # Desactivamos el control de login de Unfold para usar nuestro propio sistema
    "LOGIN": {
        "image": lambda request: static("img/login-bg.jpg"),
        "redirect_after": reverse_lazy("admin:index"),
    },
    "BORDER_RADIUS": "6px",
    "COLORS": {
        "base": {
            "50": "249 250 251",
            "100": "243 244 246",
            "200": "229 231 235",
            "300": "209 213 219",
            "400": "156 163 175",
            "500": "107 114 128",
            "600": "75 85 99",
            "700": "55 65 81",
            "800": "31 41 55",
            "900": "17 24 39",
            "950": "3 7 18",
        },
        "primary": {
            "50": "250 245 255",
            "100": "243 232 255",
            "200": "233 213 255",
            "300": "216 180 254",
            "400": "192 132 252",
            "500": "168 85 247",
            "600": "147 51 234",
            "700": "126 34 206",
            "800": "107 33 168",
            "900": "88 28 135",
            "950": "59 7 100",
        },
        "font": {
            "subtle-light": "var(--color-base-500)",
            "subtle-dark": "var(--color-base-400)",
            "default-light": "var(--color-base-600)",
            "default-dark": "var(--color-base-300)",
            "important-light": "var(--color-base-900)",
            "important-dark": "var(--color-base-100)",
        },
    },
    "SIDEBAR": {
        "show_search": True,
        "show_all_applications": True,
        "navigation": [
            {
                "title": _("Dashboard"),
                "separator": True,
                "collapsible": False,
                "items": [
                    {
                        "title": _("Dashboard"),
                        "icon": "dashboard",
                        "link": reverse_lazy("admin:index"),
                        "permission": lambda request: request.user.is_staff,
                    },
                ],
            },
            {
                "title": _("Administración"),
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": _("Usuarios"),
                        "icon": "person",
                        "link": reverse_lazy("admin:auth_user_changelist"),
                    },
                    {
                        "title": _("Grupos"),
                        "icon": "group",
                        "link": reverse_lazy("admin:auth_group_changelist"),
                    },
                    {
                        "title": _("Logs del Sistema"),
                        "icon": "history",
                        "link": reverse_lazy("admin:admin_logentry_changelist"),
                        "permission": lambda request: request.user.is_superuser,
                    },
                ],
            },
            {
                "title": _("Inventarios"),
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": _("Inventario"),
                        "icon": "inventory_2",
                        "link": reverse_lazy("admin:inventarios_inventario_changelist"),
                    },
                    {
                        "title": _("Items"),
                        "icon": "inventory",
                        "link": reverse_lazy("admin:inventarios_item_changelist"),
                    },
                    {
                        "title": _("Bodegas"),
                        "icon": "warehouse",
                        "link": reverse_lazy("admin:inventarios_bodega_changelist"),
                    },
                    {
                        "title": _("Proveedores"),
                        "icon": "local_shipping",
                        "link": reverse_lazy("admin:inventarios_proveedor_changelist"),
                    },
                    {
                        "title": _("Movimientos"),
                        "icon": "sync_alt",
                        "link": reverse_lazy("admin:inventarios_movimiento_changelist"),
                    },
                ],
            },
            {
                "title": _("Comercial"),
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": _("Pedidos"),
                        "icon": "shopping_cart",
                        "link": reverse_lazy("admin:comercial_pedido_changelist"),
                    },
                    {
                        "title": _("Detalle Pedidos"),
                        "icon": "list_alt",
                        "link": reverse_lazy("admin:comercial_detallepedido_changelist"),
                    },
                    {
                        "title": _("Clientes"),
                        "icon": "people_alt",
                        "link": reverse_lazy("admin:comercial_cliente_changelist"),
                    },
                    {
                        "title": _("Exportadores"),
                        "icon": "flight_takeoff",
                        "link": reverse_lazy("admin:comercial_exportador_changelist"),
                    },
                    {
                        "title": _("Referencias"),
                        "icon": "label",
                        "link": reverse_lazy("admin:comercial_referencias_changelist"),
                    },
                    {
                        "title": _("Frutas"),
                        "icon": "nutrition",
                        "link": reverse_lazy("admin:comercial_fruta_changelist"),
                    },
                    {
                        "title": _("Presentaciones"),
                        "icon": "category",
                        "link": reverse_lazy("admin:comercial_presentacion_changelist"),
                    },
                    {
                        "title": _("Tipos de Caja"),
                        "icon": "dataset",
                        "link": reverse_lazy("admin:comercial_tipocaja_changelist"),
                    },
                    {
                        "title": _("Contenedores"),
                        "icon": "forest",
                        "link": reverse_lazy("admin:comercial_contenedor_changelist"),
                    },
                    {
                        "title": _("Aerolíneas"),
                        "icon": "flight",
                        "link": reverse_lazy("admin:comercial_aerolinea_changelist"),
                    },
                    {
                        "title": _("Destinos IATA"),
                        "icon": "location_on",
                        "link": reverse_lazy("admin:comercial_iata_changelist"),
                    },
                    {
                        "title": _("Agencias de Carga"),
                        "icon": "local_shipping",
                        "link": reverse_lazy("admin:comercial_agenciacarga_changelist"),
                    },
                    {
                        "title": _("SubExportadoras"),
                        "icon": "local_shipping",
                        "link": reverse_lazy("admin:comercial_subexportadora_changelist"),
                    },
                    {
                        "title": _("Intermediarios"),
                        "icon": "person",
                        "link": reverse_lazy("admin:comercial_intermediario_changelist"),
                    },
                    {
                        "title": _("Presentacion Referencia"),
                        "icon": "category",
                        "link": reverse_lazy("admin:comercial_presentacionreferencia_changelist"),
                    },
                    {
                        "title": _("Autorizacion Cancelacion"),
                        "icon": "cancel",
                        "link": reverse_lazy("admin:comercial_autorizacioncancelacion_changelist"),
                    },
                    {
                        "title": _("Cliente Presentacion"),
                        "icon": "people",
                        "link": reverse_lazy("admin:comercial_clientepresentacion_changelist"),
                    },
                ],
            },
            {
                "title": _("Nacionales"),
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": _("Compras Nacionales"),
                        "icon": "shopping_bag",
                        "link": reverse_lazy("admin:nacionales_compranacional_changelist"),
                    },
                    {
                        "title": _("Ventas Nacionales"),
                        "icon": "sell",
                        "link": reverse_lazy("admin:nacionales_ventanacional_changelist"),
                    },
                    {
                        "title": _("Reporte Calidad Exportador"),
                        "icon": "assessment",
                        "link": reverse_lazy("admin:nacionales_reportecalidadexportador_changelist"),
                    },
                    {
                        "title": _("Reporte Calidad Proveedor"),
                        "icon": "source",
                        "link": reverse_lazy("admin:nacionales_reportecalidadproveedor_changelist"),
                    },
                    {
                        "title": _("Proveedores Nacionales"),
                        "icon": "handshake",
                        "link": reverse_lazy("admin:nacionales_proveedornacional_changelist"),
                    },
                    {
                        "title": _("Empaques"),
                        "icon": "inventory_2",
                        "link": reverse_lazy("admin:nacionales_empaque_changelist"),
                    },
                    {
                        "title": _("Transferencias"),
                        "icon": "swap_horiz",
                        "link": reverse_lazy("admin:nacionales_transferenciasproveedor_changelist"),
                    },
                    {
                        "title": _("Balance Proveedor"),
                        "icon": "account_balance",
                        "link": reverse_lazy("admin:nacionales_balanceproveedor_changelist"),
                    },
                ],
            },
            {
                "title": _("Cartera"),
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": _("Cotización Etnico"),
                        "icon": "attach_money",
                        "link": reverse_lazy("admin:cartera_cotizacionetnico_changelist"),
                    },
                    {
                        "title": _("Cotización Fieldex"),
                        "icon": "monetization_on",
                        "link": reverse_lazy("admin:cartera_cotizacionfieldex_changelist"),
                    },
                    {
                        "title": _("Cotización Juan"),
                        "icon": "paid",
                        "link": reverse_lazy("admin:cartera_cotizacionjuan_changelist"),
                    },
                ],
            },
        ],
    },
}

# Captcha Configuration
CAPTCHA_FONT_SIZE = 40
CAPTCHA_LENGTH = 6
CAPTCHA_TIMEOUT = 5
CAPTCHA_CHALLENGE_FUNCT = 'captcha.helpers.random_char_challenge'
