# Generated by Django 6.0 on 2025-12-28 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['-fecha_movimiento']},
        ),
        migrations.AlterModelOptions(
            name='movimiento',
            options={'ordering': ['-fecha_movimiento']},
        ),
    ]
