# Generated by Django 5.0.1 on 2024-01-26 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0002_remove_movimiento_validador'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimiento',
            name='validador',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Validador'),
        ),
    ]
