# Generated by Django 5.0.1 on 2024-01-26 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0003_movimiento_validador'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimiento',
            name='validador',
        ),
    ]
