# Generated by Django 5.0.1 on 2024-01-26 03:25

import django.core.validators
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True, verbose_name='Nombre Cliente')),
                ('direccion', models.CharField(max_length=255, verbose_name='Dirección')),
                ('ciudad', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ciudad')),
                ('tax_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tax ID')),
                ('incoterm', models.CharField(blank=True, max_length=50, null=True, verbose_name='Incoterm')),
                ('agencia_de_carga', models.CharField(blank=True, max_length=100, null=True, verbose_name='Agencia De Carga')),
                ('correo', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo')),
                ('correo2', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo 2')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefono')),
                ('intermediario', models.CharField(blank=True, max_length=100, null=True, verbose_name='Intermediario')),
                ('direccion2', models.CharField(blank=True, max_length=255, null=True, verbose_name='Direccion 2')),
                ('ciudad2', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ciudad 2')),
                ('tax_id2', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tax ID2')),
                ('encargado_de_reservar', models.CharField(blank=True, max_length=100, null=True, verbose_name='Reservar')),
                ('negociaciones_cartera', models.IntegerField(verbose_name='Dias Cartera')),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Contenedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True, verbose_name='Nombre del Contenedor')),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Exportador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Fruta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Presentacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='Presentación')),
                ('kilos', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Kilos')),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='TipoCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='Tipo De Caja')),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalPedido',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('fecha_solicitud', models.DateField(verbose_name='Fecha Solicitud')),
                ('fecha_entrega', models.DateField(verbose_name='Fecha Entrega')),
                ('dias_cartera', models.IntegerField(blank=True, editable=False, null=True, verbose_name='Dias Cartera')),
                ('awb', models.CharField(blank=True, max_length=50, null=True, verbose_name='AWB')),
                ('destino', models.CharField(blank=True, editable=False, max_length=50, null=True, verbose_name='Destino')),
                ('numero_factura', models.CharField(blank=True, max_length=50, null=True, verbose_name='Factura')),
                ('total_cajas_enviadas', models.IntegerField(blank=True, editable=False, null=True, verbose_name='Cajas Enviadas')),
                ('nota_credito_no', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nota Crédito')),
                ('motivo_nota_credito', models.CharField(blank=True, choices=[('Calidad', 'Calidad'), ('Faltantes', 'Faltantes'), ('Precio', 'Precio')], max_length=20, null=True, verbose_name='Motivo Nota Crédito')),
                ('descuento', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='$Descuento C')),
                ('valor_total_nota_credito_usd', models.DecimalField(blank=True, decimal_places=2, default=0, editable=False, max_digits=10, null=True, verbose_name='$Total Nota Crédito')),
                ('tasa_representativa_usd_diaria', models.DecimalField(blank=True, decimal_places=2, default=0, editable=False, max_digits=10, null=True, verbose_name='$TRM Oficial')),
                ('valor_pagado_cliente_usd', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='$Pagado Cliente')),
                ('comision_bancaria_usd', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='$Comisión Bancaria USD')),
                ('fecha_pago', models.DateField(blank=True, null=True, verbose_name='Fecha Pago Cliente')),
                ('fecha_monetizacion', models.DateField(blank=True, null=True, verbose_name='Fecha Monetización')),
                ('trm_monetizacion', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='$TRM Monetización')),
                ('estado_factura', models.CharField(blank=True, editable=False, max_length=50, null=True, verbose_name='Estado Factura')),
                ('diferencia_por_abono', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True, verbose_name='Diferencia o Abono')),
                ('dias_de_vencimiento', models.IntegerField(blank=True, editable=False, null=True, verbose_name='Dias Vencimiento')),
                ('valor_total_factura_usd', models.DecimalField(blank=True, decimal_places=2, default=0, editable=False, max_digits=10, null=True, verbose_name='$Total Factura')),
                ('valor_total_comision_usd', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True, verbose_name='$Comisiones USD')),
                ('valor_comision_pesos', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True, verbose_name='$Comisiones Pesos')),
                ('documento_cobro_comision', models.CharField(blank=True, max_length=50, null=True, verbose_name='Doc Cobro Comisión')),
                ('fecha_pago_comision', models.DateField(blank=True, null=True, verbose_name='Fecha Pago Comisión')),
                ('estado_comision', models.CharField(editable=False, max_length=50, verbose_name='Estado Comisión')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('cliente', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='comercial.cliente', verbose_name='Cliente')),
                ('exportadora', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='comercial.exportador', verbose_name='Exportador')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical pedido',
                'verbose_name_plural': 'historical pedidos',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddField(
            model_name='cliente',
            name='pais',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comercial.pais', verbose_name='Pais'),
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_solicitud', models.DateField(verbose_name='Fecha Solicitud')),
                ('fecha_entrega', models.DateField(verbose_name='Fecha Entrega')),
                ('dias_cartera', models.IntegerField(blank=True, editable=False, null=True, verbose_name='Dias Cartera')),
                ('awb', models.CharField(blank=True, max_length=50, null=True, verbose_name='AWB')),
                ('destino', models.CharField(blank=True, editable=False, max_length=50, null=True, verbose_name='Destino')),
                ('numero_factura', models.CharField(blank=True, max_length=50, null=True, verbose_name='Factura')),
                ('total_cajas_enviadas', models.IntegerField(blank=True, editable=False, null=True, verbose_name='Cajas Enviadas')),
                ('nota_credito_no', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nota Crédito')),
                ('motivo_nota_credito', models.CharField(blank=True, choices=[('Calidad', 'Calidad'), ('Faltantes', 'Faltantes'), ('Precio', 'Precio')], max_length=20, null=True, verbose_name='Motivo Nota Crédito')),
                ('descuento', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='$Descuento C')),
                ('valor_total_nota_credito_usd', models.DecimalField(blank=True, decimal_places=2, default=0, editable=False, max_digits=10, null=True, verbose_name='$Total Nota Crédito')),
                ('tasa_representativa_usd_diaria', models.DecimalField(blank=True, decimal_places=2, default=0, editable=False, max_digits=10, null=True, verbose_name='$TRM Oficial')),
                ('valor_pagado_cliente_usd', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='$Pagado Cliente')),
                ('comision_bancaria_usd', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='$Comisión Bancaria USD')),
                ('fecha_pago', models.DateField(blank=True, null=True, verbose_name='Fecha Pago Cliente')),
                ('fecha_monetizacion', models.DateField(blank=True, null=True, verbose_name='Fecha Monetización')),
                ('trm_monetizacion', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='$TRM Monetización')),
                ('estado_factura', models.CharField(blank=True, editable=False, max_length=50, null=True, verbose_name='Estado Factura')),
                ('diferencia_por_abono', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True, verbose_name='Diferencia o Abono')),
                ('dias_de_vencimiento', models.IntegerField(blank=True, editable=False, null=True, verbose_name='Dias Vencimiento')),
                ('valor_total_factura_usd', models.DecimalField(blank=True, decimal_places=2, default=0, editable=False, max_digits=10, null=True, verbose_name='$Total Factura')),
                ('valor_total_comision_usd', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True, verbose_name='$Comisiones USD')),
                ('valor_comision_pesos', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True, verbose_name='$Comisiones Pesos')),
                ('documento_cobro_comision', models.CharField(blank=True, max_length=50, null=True, verbose_name='Doc Cobro Comisión')),
                ('fecha_pago_comision', models.DateField(blank=True, null=True, verbose_name='Fecha Pago Comisión')),
                ('estado_comision', models.CharField(editable=False, max_length=50, verbose_name='Estado Comisión')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comercial.cliente', verbose_name='Cliente')),
                ('exportadora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comercial.exportador', verbose_name='Exportador')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ClientePresentacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comercial.cliente')),
                ('presentacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comercial.presentacion')),
            ],
            options={
                'ordering': ['cliente'],
            },
        ),
        migrations.AddField(
            model_name='cliente',
            name='presentaciones',
            field=models.ManyToManyField(related_name='clientes', through='comercial.ClientePresentacion', to='comercial.presentacion'),
        ),
        migrations.CreateModel(
            name='Referencias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='Referencia')),
                ('referencia_nueva', models.CharField(blank=True, max_length=255, null=True, verbose_name='Referencia Nueva')),
                ('cant_contenedor', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cantidad Cajas En Contenedor')),
                ('precio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio')),
                ('contenedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='comercial.contenedor', verbose_name='Contenedor')),
                ('exportador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comercial.exportador', verbose_name='Exportador')),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalDetallePedido',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('cajas_solicitadas', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cajas Solicitadas')),
                ('presentacion_peso', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=5, null=True, verbose_name='Peso Caja')),
                ('kilos', models.DecimalField(decimal_places=2, editable=False, max_digits=10, verbose_name='Kilos Netos')),
                ('cajas_enviadas', models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cajas Enviadas')),
                ('kilos_enviados', models.DecimalField(decimal_places=2, editable=False, max_digits=10, verbose_name='Kilos Enviados')),
                ('diferencia', models.DecimalField(decimal_places=2, editable=False, max_digits=10, verbose_name='Diferencia')),
                ('stickers', models.CharField(blank=True, editable=False, max_length=255, null=True, verbose_name='Stickers')),
                ('lleva_contenedor', models.BooleanField(choices=[(True, 'Sí'), (False, 'No')], verbose_name='LLeva Contenedor')),
                ('referencia_contenedor', models.CharField(blank=True, editable=False, max_length=255, null=True, verbose_name='Contenedor')),
                ('cantidad_contenedores', models.IntegerField(blank=True, editable=False, null=True, verbose_name='No. Contenedores')),
                ('tarifa_comision', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='$Comisión Por Caja')),
                ('valor_x_caja_usd', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='$Por Caja USD')),
                ('valor_x_producto', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True, verbose_name='$Por Producto')),
                ('no_cajas_nc', models.IntegerField(blank=True, null=True, verbose_name='No Cajas NC')),
                ('valor_nota_credito_usd', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True, verbose_name='$Nota Crédito USD')),
                ('afecta_comision', models.BooleanField(blank=True, choices=[(True, 'Sí'), (False, 'No')], null=True, verbose_name='Afecta Comisión')),
                ('valor_total_comision_x_producto', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True, verbose_name='$Comisión X Producto')),
                ('precio_proforma', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='$Proforma')),
                ('observaciones', models.CharField(blank=True, max_length=100, null=True, verbose_name='Observaciones')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('fruta', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='comercial.fruta', verbose_name='Fruta')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('pedido', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='comercial.pedido', verbose_name='Pedido')),
                ('presentacion', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='comercial.presentacion', verbose_name='Presentación')),
                ('referencia', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='comercial.referencias', verbose_name='Referencia')),
                ('tipo_caja', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='comercial.tipocaja', verbose_name='Marca Caja')),
            ],
            options={
                'verbose_name': 'historical detalle pedido',
                'verbose_name_plural': 'historical detalle pedidos',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cajas_solicitadas', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cajas Solicitadas')),
                ('presentacion_peso', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=5, null=True, verbose_name='Peso Caja')),
                ('kilos', models.DecimalField(decimal_places=2, editable=False, max_digits=10, verbose_name='Kilos Netos')),
                ('cajas_enviadas', models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cajas Enviadas')),
                ('kilos_enviados', models.DecimalField(decimal_places=2, editable=False, max_digits=10, verbose_name='Kilos Enviados')),
                ('diferencia', models.DecimalField(decimal_places=2, editable=False, max_digits=10, verbose_name='Diferencia')),
                ('stickers', models.CharField(blank=True, editable=False, max_length=255, null=True, verbose_name='Stickers')),
                ('lleva_contenedor', models.BooleanField(choices=[(True, 'Sí'), (False, 'No')], verbose_name='LLeva Contenedor')),
                ('referencia_contenedor', models.CharField(blank=True, editable=False, max_length=255, null=True, verbose_name='Contenedor')),
                ('cantidad_contenedores', models.IntegerField(blank=True, editable=False, null=True, verbose_name='No. Contenedores')),
                ('tarifa_comision', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='$Comisión Por Caja')),
                ('valor_x_caja_usd', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='$Por Caja USD')),
                ('valor_x_producto', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True, verbose_name='$Por Producto')),
                ('no_cajas_nc', models.IntegerField(blank=True, null=True, verbose_name='No Cajas NC')),
                ('valor_nota_credito_usd', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True, verbose_name='$Nota Crédito USD')),
                ('afecta_comision', models.BooleanField(blank=True, choices=[(True, 'Sí'), (False, 'No')], null=True, verbose_name='Afecta Comisión')),
                ('valor_total_comision_x_producto', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True, verbose_name='$Comisión X Producto')),
                ('precio_proforma', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='$Proforma')),
                ('observaciones', models.CharField(blank=True, max_length=100, null=True, verbose_name='Observaciones')),
                ('fruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comercial.fruta', verbose_name='Fruta')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comercial.pedido', verbose_name='Pedido')),
                ('presentacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comercial.presentacion', verbose_name='Presentación')),
                ('referencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comercial.referencias', verbose_name='Referencia')),
                ('tipo_caja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comercial.tipocaja', verbose_name='Marca Caja')),
            ],
            options={
                'ordering': ['pedido'],
            },
        ),
    ]
