# Generated by Django 5.0.1 on 2024-01-26 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallepedido',
            name='afecta_comision',
            field=models.BooleanField(blank=True, choices=[(True, 'Sí'), (False, 'No'), (None, 'Descuento')], null=True, verbose_name='Afecta Comisión'),
        ),
        migrations.AlterField(
            model_name='historicaldetallepedido',
            name='afecta_comision',
            field=models.BooleanField(blank=True, choices=[(True, 'Sí'), (False, 'No'), (None, 'Descuento')], null=True, verbose_name='Afecta Comisión'),
        ),
    ]
