# Generated by Django 5.0.7 on 2024-07-29 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpedido',
            name='estado_cancelacion',
            field=models.CharField(choices=[('sin_solicitud', 'Sin solicitud'), ('pendiente', 'Pendiente'), ('autorizado', 'Autorizado'), ('no_autorizado', 'No Autorizado')], default='sin_solicitud', editable=False, max_length=20, verbose_name='Estado Cancelación'),
        ),
        migrations.AlterField(
            model_name='historicalpedido',
            name='tasa_representativa_usd_diaria',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, editable=False, max_digits=10, null=True, verbose_name='$TRM Oficial'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado_cancelacion',
            field=models.CharField(choices=[('sin_solicitud', 'Sin solicitud'), ('pendiente', 'Pendiente'), ('autorizado', 'Autorizado'), ('no_autorizado', 'No Autorizado')], default='sin_solicitud', editable=False, max_length=20, verbose_name='Estado Cancelación'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='tasa_representativa_usd_diaria',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, editable=False, max_digits=10, null=True, verbose_name='$TRM Oficial'),
        ),
    ]
