# Generated by Django 5.0.1 on 2024-06-15 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0002_alter_detallepedido_afecta_comision_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallepedido',
            name='afecta_comision',
            field=models.BooleanField(blank=True, choices=[(True, 'Sí'), (False, 'No'), (None, 'Descuento')], default=False, null=True, verbose_name='Afecta Comisión'),
        ),
        migrations.AlterField(
            model_name='historicaldetallepedido',
            name='afecta_comision',
            field=models.BooleanField(blank=True, choices=[(True, 'Sí'), (False, 'No'), (None, 'Descuento')], default=False, null=True, verbose_name='Afecta Comisión'),
        ),
        migrations.AlterField(
            model_name='historicalpedido',
            name='tasa_representativa_usd_diaria',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='$TRM Oficial'),
        ),
        migrations.AlterField(
            model_name='historicalpedido',
            name='valor_comision_pesos',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, editable=False, max_digits=10, null=True, verbose_name='$Comisiones Pesos'),
        ),
        migrations.AlterField(
            model_name='historicalpedido',
            name='valor_total_comision_usd',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, editable=False, max_digits=10, null=True, verbose_name='$Comisiones USD'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='tasa_representativa_usd_diaria',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='$TRM Oficial'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='valor_comision_pesos',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, editable=False, max_digits=10, null=True, verbose_name='$Comisiones Pesos'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='valor_total_comision_usd',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, editable=False, max_digits=10, null=True, verbose_name='$Comisiones USD'),
        ),
        migrations.AlterUniqueTogether(
            name='clientepresentacion',
            unique_together={('cliente', 'presentacion')},
        ),
        migrations.AlterUniqueTogether(
            name='presentacion',
            unique_together={('nombre', 'kilos')},
        ),
    ]
