# Generated by Django 5.0.7 on 2024-07-31 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0002_alter_historicalpedido_estado_cancelacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpedido',
            name='semana',
            field=models.CharField(blank=True, editable=False, null=True, verbose_name='Semana'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='semana',
            field=models.CharField(blank=True, editable=False, null=True, verbose_name='Semana'),
        ),
    ]
