# Generated by Django 5.1.4 on 2024-12-26 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0002_alter_detallepedido_no_cajas_nc_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='presentacionreferencia',
            constraint=models.UniqueConstraint(fields=('presentacion', 'referencia', 'fruta', 'tipo_caja'), name='unique_presentacion_referencia'),
        ),
    ]
