# Generated by Django 5.1.4 on 2024-12-28 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0003_presentacionreferencia_unique_presentacion_referencia'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pedido',
            options={},
        ),
        migrations.AddIndex(
            model_name='detallepedido',
            index=models.Index(fields=['pedido'], name='comercial_d_pedido__220586_idx'),
        ),
        migrations.AddIndex(
            model_name='detallepedido',
            index=models.Index(fields=['fruta'], name='comercial_d_fruta_i_806157_idx'),
        ),
        migrations.AddIndex(
            model_name='detallepedido',
            index=models.Index(fields=['referencia'], name='comercial_d_referen_e1dca4_idx'),
        ),
        migrations.AddIndex(
            model_name='detallepedido',
            index=models.Index(fields=['presentacion'], name='comercial_d_present_60654e_idx'),
        ),
    ]
