# Generated by Django 5.1.4 on 2024-12-28 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0004_alter_pedido_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='autorizacioncancelacion',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='pedido',
            options={'ordering': ['-id']},
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['cliente'], name='comercial_p_cliente_de338f_idx'),
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['exportadora'], name='comercial_p_exporta_8d77bb_idx'),
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['awb'], name='comercial_p_awb_e40220_idx'),
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['numero_factura'], name='comercial_p_numero__14fbc9_idx'),
        ),
    ]
