# Generated by Django 5.1.4 on 2024-12-28 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0005_alter_autorizacioncancelacion_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='autorizacioncancelacion',
            options={'ordering': ['pedido']},
        ),
    ]
