# Generated by Django 5.1.5 on 2025-03-03 23:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0006_alter_autorizacioncancelacion_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallepedido',
            name='tarifa_recuperacion',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='$Recuperación Por Caja'),
        ),
        migrations.AddField(
            model_name='detallepedido',
            name='valor_total_recuperacion_x_producto',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True, verbose_name='$Recuperación X Producto'),
        ),
        migrations.AddField(
            model_name='historicaldetallepedido',
            name='tarifa_recuperacion',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='$Recuperación Por Caja'),
        ),
        migrations.AddField(
            model_name='historicaldetallepedido',
            name='valor_total_recuperacion_x_producto',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True, verbose_name='$Recuperación X Producto'),
        ),
    ]
