# Generated by Django 5.1.5 on 2025-03-04 02:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0007_detallepedido_tarifa_recuperacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallepedido',
            name='tarifa_recuperacion',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='$ Recuperacion'),
        ),
        migrations.AlterField(
            model_name='historicaldetallepedido',
            name='tarifa_recuperacion',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='$ Recuperacion'),
        ),
    ]
