# Generated by Django 5.1.7 on 2025-03-13 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0007_detallepedido_tarifa_recuperacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpedido',
            name='valor_total_recuperacion_usd',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, editable=False, max_digits=10, null=True, verbose_name='$ Recuperaciónes USD'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='valor_total_recuperacion_usd',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, editable=False, max_digits=10, null=True, verbose_name='$ Recuperaciónes USD'),
        ),
        migrations.AlterField(
            model_name='historicalpedido',
            name='valor_total_utilidad_usd',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, editable=False, max_digits=10, null=True, verbose_name='$ Utilidades USD'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='valor_total_utilidad_usd',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, editable=False, max_digits=10, null=True, verbose_name='$ Utilidades USD'),
        ),
    ]
