# Generated by Django 5.2 on 2025-05-02 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0008_historicalpedido_valor_total_recuperacion_usd_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fruta',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción'),
        ),
        migrations.AddField(
            model_name='fruta',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='frutas/', verbose_name='Imagen'),
        ),
    ]
