# Generated by Django 5.2 on 2025-05-07 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0009_fruta_descripcion_fruta_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='fruta',
            name='descripcion_en',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción en inglés'),
        ),
        migrations.AddField(
            model_name='fruta',
            name='nombre_en',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Nombre en inglés'),
        ),
    ]
