# Generated by Django 6.0 on 2025-12-28 12:32

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0010_fruta_descripcion_en_fruta_nombre_en'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CostosEstibado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Costos Estibado General', help_text='Identificador para este conjunto de costos', max_length=100, verbose_name='Nombre/Descripción')),
                ('estiba', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Estiba')),
                ('malla_tela', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Malla Tela')),
                ('malla_termica', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Malla Termica')),
                ('esquineros_zuncho', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Esquineros Zuncho')),
                ('entrega', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Entrega')),
                ('fecha_actualizacion', models.DateField(auto_now=True)),
                ('es_activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Costos Estibado',
                'verbose_name_plural': 'Costos Estibado',
                'ordering': ['-fecha_actualizacion'],
            },
        ),
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='Insumo')),
                ('precio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio')),
                ('unidad_medida', models.CharField(blank=True, max_length=20, null=True, verbose_name='Unidad de Medida')),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.AlterModelOptions(
            name='clientepresentacion',
            options={'ordering': ['cliente', 'fruta'], 'verbose_name': 'Cliente Presentación', 'verbose_name_plural': 'Clientes Presentaciones'},
        ),
        migrations.AlterUniqueTogether(
            name='clientepresentacion',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='clientepresentacion',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='clientepresentacion',
            name='exportador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='comercial.exportador', verbose_name='Exportador Proveedor'),
        ),
        migrations.AddField(
            model_name='clientepresentacion',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='clientepresentacion',
            name='fecha_creacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='clientepresentacion',
            name='referencia',
            field=models.ForeignKey(blank=True, limit_choices_to={'exportador': models.F('exportador')}, null=True, on_delete=django.db.models.deletion.CASCADE, to='comercial.referencias', verbose_name='Referencia (Caja)'),
        ),
        migrations.AddField(
            model_name='contenedor',
            name='precio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio COP'),
        ),
        migrations.AlterField(
            model_name='clientepresentacion',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presentaciones_config', to='comercial.cliente'),
        ),
        migrations.AlterUniqueTogether(
            name='clientepresentacion',
            unique_together={('cliente', 'presentacion', 'fruta', 'exportador')},
        ),
        migrations.CreateModel(
            name='CostoPresentacionCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mano_obra_cop', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Mano de Obra COP por Kg')),
                ('deshidratacion_fruta', models.DecimalField(decimal_places=2, default=0, help_text='Porcentaje de deshidratación a sumar por caja. Ej: 1.25 aplica +1.25% sobre los kilos de la presentación', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Deshidratación Fruta (%)')),
                ('margen_adicional_usd', models.DecimalField(decimal_places=2, default=0, help_text='Margen que aplicas a esta venta específica / se divide en Heavens y Exportador', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Margen Adicional USD por Caja')),
                ('es_activo', models.BooleanField(default=True, verbose_name='¿Es Activo?')),
                ('fecha_inicio', models.DateField(auto_now_add=True, verbose_name='Fecha Inicio Vigencia')),
                ('fecha_fin', models.DateField(blank=True, null=True, verbose_name='Fecha Fin Vigencia (dejar vacío para vigencia indefinida)')),
                ('aprobada', models.BooleanField(default=False)),
                ('fecha_aprobacion', models.DateTimeField(blank=True, null=True)),
                ('trm_aprobacion', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('desglose_aprobado', models.JSONField(blank=True, default=None, null=True)),
                ('cliente_presentacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='costos_contextuales', to='comercial.clientepresentacion')),
            ],
            options={
                'verbose_name': 'Costo Presentación Cliente',
                'verbose_name_plural': 'Costos Presentaciones Clientes',
                'ordering': ['-fecha_inicio'],
                'indexes': [models.Index(fields=['cliente_presentacion'], name='comercial_c_cliente_c4219a_idx'), models.Index(fields=['es_activo'], name='comercial_c_es_acti_58a757_idx')],
                'unique_together': {('cliente_presentacion',)},
            },
        ),
        migrations.CreateModel(
            name='CostosUnicosEmbarque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transporte_aeropuerto', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Transporte Aeropuerto')),
                ('termo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Termoregistro')),
                ('precinto', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precinto')),
                ('aduana', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Aduana')),
                ('comision_bancaria', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Comisión Bancaria')),
                ('due_agent_usd', models.DecimalField(blank=True, decimal_places=2, help_text='Costo en USD, solo aplica para negociación CIF', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Due Agent (USD)')),
                ('due_carrier_usd', models.DecimalField(blank=True, decimal_places=2, help_text='Costo en USD, solo aplica para negociación CIF', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Due Carrier (USD)')),
                ('fito_usd', models.DecimalField(blank=True, decimal_places=2, help_text='Costo en USD, solo aplica para negociación CIF', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Fito (USD)')),
                ('certificado_origen_usd', models.DecimalField(blank=True, decimal_places=2, help_text='Costo en USD, solo aplica para negociación CIF', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Certificado Origen (USD)')),
                ('fecha_actualizacion', models.DateField(auto_now=True)),
                ('es_activo', models.BooleanField(default=True)),
                ('aerolinea', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='costos_embarque', to='comercial.aerolinea', verbose_name='Aerolinea (opcional)')),
                ('destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='costos_embarque', to='comercial.iata', verbose_name='Destino (opcional)')),
            ],
            options={
                'verbose_name': 'Costos Únicos Embarque',
                'verbose_name_plural': 'Costos Únicos Embarque',
                'ordering': ['-fecha_actualizacion'],
                'unique_together': {('aerolinea', 'destino')},
            },
        ),
        migrations.CreateModel(
            name='CotizacionConjuntaHistorico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_cotizacion', models.CharField(help_text='Identificador único generado automáticamente', max_length=50, unique=True, verbose_name='Número de Cotización')),
                ('tipo_negociacion', models.CharField(choices=[('CIF', 'CIF'), ('FOB', 'FOB')], default='CIF', max_length=3, verbose_name='Tipo de Negociación')),
                ('trm', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='TRM Usado')),
                ('utilidad_general_pct', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Utilidad General (%)')),
                ('heavens_pct', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='% Heavens')),
                ('exportador_pct', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='% Exportador')),
                ('total_cajas', models.IntegerField(verbose_name='Total Cajas')),
                ('total_pallets', models.IntegerField(verbose_name='Total Pallets')),
                ('estibado_por_caja_usd', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Estibado por Caja USD')),
                ('cabecera_snapshot', models.JSONField(help_text='Nombres de cliente, aerolínea, destino tal como estaban en ese momento', verbose_name='Cabecera Snapshot')),
                ('costos_globales_snapshot', models.JSONField(help_text='Costos de embarque, estibado y tarifa aérea usados en el cálculo', verbose_name='Costos Globales Snapshot')),
                ('items_snapshot', models.JSONField(help_text='Lista completa de productos con todos los valores calculados y datos usados', verbose_name='Items Snapshot')),
                ('totales_snapshot', models.JSONField(blank=True, help_text='Resumen de totales y utilidades de toda la cotización', null=True, verbose_name='Totales Snapshot')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_aprobacion', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Aprobación')),
                ('notas', models.TextField(blank=True, help_text='Notas o comentarios adicionales sobre esta cotización', null=True, verbose_name='Notas')),
                ('aerolinea', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cotizaciones_historico', to='comercial.aerolinea', verbose_name='Aerolínea')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cotizaciones_historico', to='comercial.cliente', verbose_name='Cliente')),
                ('destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cotizaciones_historico', to='comercial.iata', verbose_name='Destino')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cotizaciones_aprobadas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario que Aprobó')),
            ],
            options={
                'verbose_name': 'Cotización Conjunta Histórico',
                'verbose_name_plural': 'Cotizaciones Conjuntas Histórico',
                'ordering': ['-fecha_aprobacion'],
                'indexes': [models.Index(fields=['cliente', 'fecha_aprobacion'], name='comercial_c_cliente_306e12_idx'), models.Index(fields=['numero_cotizacion'], name='comercial_c_numero__d9bc2b_idx')],
            },
        ),
        migrations.CreateModel(
            name='ListaPreciosFrutaExportador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_kilo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio Kg')),
                ('fecha', models.DateField(auto_now=True, verbose_name='Fecha Ultima Actualización')),
                ('precio_anterior', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio Anterior')),
                ('exportadora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comercial.exportador')),
                ('fruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comercial.fruta')),
            ],
            options={
                'ordering': ['fruta', 'exportadora', '-fecha'],
                'unique_together': {('fruta', 'exportadora')},
            },
        ),
        migrations.CreateModel(
            name='PresentacionInsumoCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cantidad Personalizada')),
                ('cliente_presentacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insumos_personalizados', to='comercial.clientepresentacion')),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comercial.insumo')),
            ],
            options={
                'verbose_name': 'Presentación Insumo Cliente',
                'verbose_name_plural': 'Presentaciones Insumos Clientes',
                'ordering': ['cliente_presentacion'],
                'unique_together': {('cliente_presentacion', 'insumo')},
            },
        ),
        migrations.CreateModel(
            name='TarifaAerea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarifa_por_kilo', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Tarifa USD/Kg')),
                ('fecha', models.DateField(auto_now=True, verbose_name='Fecha Ultima Actualización')),
                ('es_activa', models.BooleanField(default=True)),
                ('aerolinea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarifas', to='comercial.aerolinea')),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comercial.iata', verbose_name='Destino')),
            ],
            options={
                'verbose_name_plural': 'Tarifas Aéreas',
                'ordering': ['aerolinea', 'destino', '-fecha'],
                'unique_together': {('aerolinea', 'destino')},
            },
        ),
    ]
