# Generated by Django 6.0 on 2026-01-31 21:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0011_costosestibado_insumo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallepedido',
            name='porcentaje_afectacion_utilidad',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Porcentaje de afectación de la utilidad para Juan Matas (0-100)', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='% Afectación Utilidad'),
        ),
        migrations.AddField(
            model_name='historicaldetallepedido',
            name='porcentaje_afectacion_utilidad',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Porcentaje de afectación de la utilidad para Juan Matas (0-100)', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='% Afectación Utilidad'),
        ),
    ]
