from django.urls import path
from . import views

urlpatterns = [
    path('pedido_detalles/<int:pedido_id>', views.DetallePedidoListView.as_view(), name='pedido_detalle_list'),
    path('pedido_list_general', views.PedidoListView.as_view(), name='pedido_list_general'),
    path('pedido_crear', views.PedidoCreateView.as_view(), name='pedido_crear'),
    path('pedido_editar', views.PedidoUpdateView.as_view(), name='pedido_editar'),
    path('pedido_eliminar', views.PedidoDeleteView.as_view(), name='pedido_eliminar'),
    path('detalle_pedido_crear/<int:pedido_id>', views.DetallePedidoCreateView.as_view(), name='detalle_pedido_crear'),
    path('detalle_pedido_editar', views.DetallePedidoUpdateView.as_view(), name='detalle_pedido_editar'),
    path('detalle_pedido_eliminar', views.DetallePedidoDeleteiew.as_view(), name='detalle_pedido_eliminar'),
    path('pedido_list_etnico', views.PedidoEtnicoListView.as_view(), name='pedido_list_etnico'),
    path('pedido_list_fieldex', views.PedidoFieldexListView.as_view(), name='pedido_list_fieldex'),
    path('pedido_list_juan', views.PedidoJuanListView.as_view(), name='pedido_list_juan'),
    path('pedido_editar_exportador', views.PedidoExportadorUpdateView.as_view(), name='pedido_editar_exportador'),
    path('cartera_list_heavens', views.CarteraHeavensListView.as_view(), name='cartera_list_heavens'),
    path('cartera_list_etnico', views.CarteraEtnicoListView.as_view(), name='cartera_list_etnico'),
    path('cartera_list_fieldex', views.CarteraFieldexListView.as_view(), name='cartera_list_fieldex'),
    path('cartera_list_juan', views.CarteraJuanListView.as_view(), name='cartera_list_juan'),
    path('exportar_cartera_clientes', views.export_cartera_clientes, name='exportar_cartera_clientes'),
    path('exportar_cartera_etnico', views.export_cartera_etnico, name='exportar_cartera_etnico'),
    path('exportar_cartera_fieldex', views.export_cartera_fieldex, name='exportar_cartera_fieldex'),
    path('exportar_cartera_juan', views.export_cartera_juan, name='exportar_cartera_juan'),
    path('exportar_pedidos_excel', views.exportar_pedidos_excel, name='exportar_pedidos_excel'),
    path('exportar_pedidos_etnico', views.exportar_pedidos_etnico, name='exportar_pedidos_etnico'),
    path('exportar_pedidos_fieldex', views.exportar_pedidos_fieldex, name='exportar_pedidos_fieldex'),
    path('exportar_pedidos_juan', views.exportar_pedidos_juan, name='exportar_pedidos_juan'),
    path('comision_list_heavens', views.ComisionHeavensListView.as_view(), name='comision_list_heavens'),
    path('comision_list_etnico', views.ComisionEtnicoListView.as_view(), name='comision_list_etnico'),
    path('comision_list_fieldex', views.ComisionFiedexListView.as_view(), name='comision_list_fieldex'),
    path('comision_list_juan', views.ComisionJuanListView.as_view(), name='comision_list_juan'),
    path('exportar_comisiones_heavens', views.exportar_comisiones_excel, name='exportar_comisiones_heavens'),
    path('exportar_comisiones_etnico', views.exportar_comisiones_etnico, name='exportar_comisiones_etnico'),
    path('exportar_comisiones_fieldex', views.exportar_comisiones_fieldex, name='exportar_comisiones_fieldex'),
    path('exportar_comisiones_juan', views.exportar_comisiones_juan, name='exportar_comisiones_juan'),
    path('exportar_detalles_p_heavens', views.exportar_detalles_pedidos_excel, name='exportar_detalles_p_heavens'),
    path('exportar_pedidos_view', views.ExportarPedidosView.as_view(), name='exportar_pedidos_view'),
    path('exportar_pedidos_etnico_view', views.ExportarPedidosEtnicoView.as_view(),
         name='exportar_pedidos_etnico_view'),
    path('exportar_pedidos_fieldex_view', views.ExportarPedidosFieldexView.as_view(),
         name='exportar_pedidos_fieldex_view'),
    path('exportar_pedidos_juan_view', views.ExportarPedidosJuanView.as_view(), name='exportar_pedidos_juan_view'),
    path('exportar_comisiones_general_view', views.ExportarComisionesView.as_view(),
         name='exportar_comisiones_general_view'),
    path('exportar_detallepedido_pdf', views.exportar_detalle_pedido_a_pdf, name='exportar_detallepedido_pdf'),
    path('pedido_resumen/<int:pedido_id>', views.ResumenPedidoListView.as_view(), name='pedido_resumen'),
    path('referencia_list_etnico', views.ReferenciasEtnicoListView.as_view(), name='referencia_list_etnico'),
    path('referencia_list_fieldex', views.ReferenciasFieldexListView.as_view(), name='referencia_list_fieldex'),
    path('referencia_list_juan', views.ReferenciasjuanListView.as_view(), name='referencia_list_juan'),
    path('referencia_editar_general', views.ReferenciaUpdateView.as_view(), name='referencia_editar_general'),
    path('exportar_referencias_etnico', views.exportar_referencias_etnico, name='exportar_referencias_etnico'),
    path('exportar_referencias_fieldex', views.exportar_referencias_fieldex, name='exportar_referencias_fieldex'),
    path('exportar_referencias_juan', views.exportar_referencias_juan, name='exportar_referencias_juan'),

]
