from django.urls import path
from . import views

urlpatterns = [
    path('pedido_detalles/<int:pedido_id>', views.DetallePedidoListView.as_view(), name='pedido_detalle_list'),
    path('pedido_list_general', views.PedidoListView.as_view(), name='pedido_list_general'),
    path('seguimiento_pedido_list_general', views.SeguimientosPedidosListView.as_view(), name='seguimiento_pedido_list_general'),
    path('pedido_crear', views.PedidoCreateView.as_view(), name='pedido_crear'),
    path('pedido_editar', views.PedidoUpdateView.as_view(), name='pedido_editar'),
    path('pedido_eliminar', views.PedidoDeleteView.as_view(), name='pedido_eliminar'),
    path('detalle_pedido_crear/<int:pedido_id>', views.DetallePedidoCreateView.as_view(), name='detalle_pedido_crear'),
    path('detalle_pedido_editar', views.DetallePedidoUpdateView.as_view(), name='detalle_pedido_editar'),
    path('detalle_pedido_eliminar', views.DetallePedidoDeleteiew.as_view(), name='detalle_pedido_eliminar'),
    path('pedido_list_etnico', views.PedidoEtnicoListView.as_view(), name='pedido_list_etnico'),
    path('pedido_list_fieldex', views.PedidoFieldexListView.as_view(), name='pedido_list_fieldex'),
    path('pedido_list_juan', views.PedidoJuanListView.as_view(), name='pedido_list_juan'),
    path('pedido_editar_exportador', views.PedidoExportadorUpdateView.as_view(), name='pedido_editar_exportador'),
    path('pedido_editar_seguimiento', views.PedidoUpdateSebguimientoView.as_view(), name='pedido_editar_seguimiento'),
    path('cartera_list_heavens', views.CarteraHeavensListView.as_view(), name='cartera_list_heavens'),
    path('resumen_seguimiento_list_heavens', views.ResumenSeguimientosPedidosListView.as_view(), name='resumen_seguimiento_list_heavens'),
    path('cartera_list_etnico', views.CarteraEtnicoListView.as_view(), name='cartera_list_etnico'),
    path('cartera_list_fieldex', views.CarteraFieldexListView.as_view(), name='cartera_list_fieldex'),
    path('cartera_list_juan', views.CarteraJuanListView.as_view(), name='cartera_list_juan'),
    path('exportar_cartera_clientes', views.export_cartera_clientes, name='exportar_cartera_clientes'),
    path('exportar_cartera_etnico', views.export_cartera_etnico, name='exportar_cartera_etnico'),
    path('exportar_cartera_fieldex', views.export_cartera_fieldex, name='exportar_cartera_fieldex'),
    path('exportar_cartera_juan', views.export_cartera_juan, name='exportar_cartera_juan'),
    path('exportar_pedidos_excel', views.exportar_pedidos_excel, name='exportar_pedidos_excel'),
    path('exportar_pedidos_etnico', views.exportar_pedidos_etnico, name='exportar_pedidos_etnico'),
    path('exportar_pedidos_fieldex', views.exportar_pedidos_fieldex, name='exportar_pedidos_fieldex'),
    path('exportar_pedidos_juan', views.exportar_pedidos_juan, name='exportar_pedidos_juan'),
    path('utilidad_list_heavens', views.UtilidadHeavensListView.as_view(), name='utilidad_list_heavens'),
    path('utilidad_list_etnico', views.UtilidadEtnicoListView.as_view(), name='utilidad_list_etnico'),
    path('utilidad_list_fieldex', views.UtilidadFiedexListView.as_view(), name='utilidad_list_fieldex'),
    path('utilidad_list_juan', views.UtilidadJuanListView.as_view(), name='utilidad_list_juan'),
    path('exportar_utilidades_heavens', views.exportar_utilidades_excel, name='exportar_utilidades_heavens'),
    path('exportar_utilidades_etnico', views.exportar_utilidades_etnico, name='exportar_utilidades_etnico'),
    path('exportar_utilidades_fieldex', views.exportar_utilidades_fieldex, name='exportar_utilidades_fieldex'),
    path('exportar_utilidades_juan', views.exportar_utilidades_juan, name='exportar_utilidades_juan'),
    path('exportar_detalles_p_heavens', views.exportar_detalles_pedidos_excel, name='exportar_detalles_p_heavens'),
    path('exportar_detalles_p_heavens_view', views.ExportarDetallesPedidoView.as_view(), name='exportar_detalles_p_heavens_view'),
    path('exportar_pedidos_view', views.ExportarPedidosView.as_view(), name='exportar_pedidos_view'),
    path('exportar_pedidos_etnico_view', views.ExportarPedidosEtnicoView.as_view(),
         name='exportar_pedidos_etnico_view'),
    path('exportar_pedidos_fieldex_view', views.ExportarPedidosFieldexView.as_view(),
         name='exportar_pedidos_fieldex_view'),
    path('exportar_pedidos_juan_view', views.ExportarPedidosJuanView.as_view(), name='exportar_pedidos_juan_view'),
    path('exportar_utilidades_general_view', views.ExportarUtilidadesView.as_view(),
         name='exportar_utilidades_general_view'),
    path('exportar_utilidades_etnico_view', views.ExportarUtilidadesEtnicoView.as_view(),
         name='exportar_utilidades_etnico_view'),
    path('exportar_utilidades_fieldex_view', views.ExportarUtilidadesFieldexView.as_view(),
         name='exportar_utilidades_fieldex_view'),
    path('exportar_utilidades_juan_view', views.ExportarUtilidadesJuanView.as_view(),
         name='exportar_utilidades_juan_view'),
    path('exportar_detallepedido_pdf', views.exportar_detalle_pedido_a_pdf, name='exportar_detallepedido_pdf'),
    path('pedido_resumen/<int:pedido_id>', views.ResumenPedidoListView.as_view(), name='pedido_resumen'),
    path('referencia_list_etnico', views.ReferenciasEtnicoListView.as_view(), name='referencia_list_etnico'),
    path('referencia_list_fieldex', views.ReferenciasFieldexListView.as_view(), name='referencia_list_fieldex'),
    path('referencia_list_juan', views.ReferenciasjuanListView.as_view(), name='referencia_list_juan'),
    path('referencia_editar_general', views.ReferenciaUpdateView.as_view(), name='referencia_editar_general'),
    path('exportar_referencias_etnico', views.exportar_referencias_etnico, name='exportar_referencias_etnico'),
    path('exportar_referencias_fieldex', views.exportar_referencias_fieldex, name='exportar_referencias_fieldex'),
    path('exportar_referencias_juan', views.exportar_referencias_juan, name='exportar_referencias_juan'),
    path('exportar_cartera_view', views.ExportarCarteraView.as_view(), name='exportar_cartera_view'),
    path('exportar_cartera_etnico_view', views.ExportarCarteraEtnicoView.as_view(), name='exportar_cartera_etnico_view'),
    path('exportar_cartera_fieldex_view', views.ExportarCarteraFieldexView.as_view(), name='exportar_cartera_fieldex_view'),
    path('exportar_cartera_juan_view', views.ExportarCarteraJuanView.as_view(), name='exportar_cartera_juan_view'),
    path('actualizar_vencimiento_general/', views.actualizar_dias_de_vencimiento_todos, name='actualizar_dias_de_vencimiento_todos'),
    path('actualizar_tasas_general/', views.actualizar_tasas, name='actualizar_tasas'),

    path('actualizar_vencimiento_etnico/', views.actualizar_dias_de_vencimiento_etnico, name='actualizar_vencimiento_etnico'),
    path('actualizar_tasas_etnico/', views.actualizar_tasas_etnico, name='actualizar_tasas_etnico'),
    path('actualizar_vencimiento_fieldex/', views.actualizar_dias_de_vencimiento_fieldex, name='actualizar_vencimiento_fieldex'),
    path('actualizar_tasas_fieldex/', views.actualizar_tasas_fieldex, name='actualizar_tasas_fieldex'),
    path('actualizar_vencimiento_juan/', views.actualizar_dias_de_vencimiento_juan, name='actualizar_vencimiento_juan'),
    path('actualizar_tasas_juan/', views.actualizar_tasas_juan, name='actualizar_tasas_juan'),



    path('pedido/<int:pedido_id>/cancelacion/', views.solicitar_cancelacion, name='solicitar_cancelacion'),
    path('autorizacion/<int:autorizacion_id>/autorizar/', views.autorizar_cancelacion, name='autorizar_cancelacion'),
    path('filtrar_presentaciones/', views.filtrar_presentaciones, name='filtrar_presentaciones'),
    path('ajax/load-referencias/', views.load_referencias, name='ajax_load_referencias'),

    path('exportar_resumen_semana_pdf/', views.export_pdf_resumen_semana, name='exportar_resumen_semana_pdf'),
    path('pedido_resumen_pdf/<int:pedido_id>', views.exportar_pdf_resumen_pedido, name='pedido_resumen_pdf'),

]
